###
GET http://127.0.0.1:5000/status HTTP/1.1

###
POST http://127.0.0.1:5000/addItem  HTTP/1.1
content-type: application/json

{
    "id": "1",
    "model": "skoda",
    "color": "red"
}
###
POST http://127.0.0.1:5000/addItem  HTTP/1.1
content-type: application/json

{
    "id": "3",
    "model": "bmw",
    "color": "green"
}
###
POST http://127.0.0.1:5000/getItem HTTP/1.1
content-type: application/json

{
    "id": "1"
}

###
GET http://127.0.0.1:5000/getItems  HTTP/1.1
